dragonfruitnetwork/dragon6-api

- Dragon6-API/Alignments.cs
- Dragon6-API/OperatorStats.cs
- Dragon6-API/PlayerStats.cs
A few stats that I went to access through the API but then found were not implemented fully.
Added to PlayerStats
WL,
MatchesPlayed,
Casual_MatchesPlayed,
Ranked_MatchesPlayed,
THunt_Wins,
THunt_Losses,
THunt_WL,
THunt_MatchesPlayed,
TimePlayed_General,
TimePlayed_Custom
Added to OperatorStats
DBNO,
RoundsPlayed
> Added more stats to PlayerStats and OperatorStats

- Dragon6-API/Dragon6-API.csproj
- Dragon6-API/Processing/Alignments.cs
- Dragon6-API/Properties/AssemblyInfo.cs
- Dragon6-API/Stats/PlayerStats.cs
this is an attempt to fix the bug (from mobile app):
```System.ArgumentNullException: Value cannot be null.
Parameter name: o
Module "Newtonsoft.Json.Linq.JToken", in FromObjectInternal
Module "Newtonsoft.Json.Linq.JObject", in FromObject
Module "Newtonsoft.Json.Linq.JObject", in FromObject
Module "Dragon6.API.Alignments", in AlignGeneralStats
Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
Module "System.Runtime.CompilerServices.TaskAwaiter", in ThrowForNonSuccess
Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
Module "System.Runtime.CompilerServices.TaskAwaiter", in ValidateEnd
Module "System.Runtime.CompilerServices.TaskAwaiter`1[[Dragon6.API.PlayerStats, Dragon6.API, Version=2019.731.0.0, Culture=neutral, …
```
> Bug fix attempt

- .travis.yml
- Dragon6-API/AccountInfo.cs
- Dragon6-API/Dragon6-API.csproj
- Dragon6-API/Http/Endpoints.cs
- Dragon6-API/Http/HttpClientPreset.cs
- Dragon6-API/Processing/Alignments.cs
- Dragon6-API/References.cs
- Dragon6-API/Stats/OperatorStats.cs
- Dragon6-API/Stats/PlayerStats.cs
- Dragon6-API/Stats/SeasonalStats.cs
- Dragon6-API/Stats/WeaponStats.cs
- Dragon6-API/Token.cs
- Dragon6-Test/Program.cs
this basically removes the duplicated HttpClient header setting and moves all the URLS to one file. This will break all stats as they have been moved to `.Stats.General`, `.Stats.Operator`, `.Stats.Weapon`, etc.
> add weapon stats and cleanup code more

- DragonFruit.Six.API/AccountInfo.cs
- DragonFruit.Six.API/DragonFruit.Six.API.csproj
- DragonFruit.Six.API/Processing/RawConvert.cs
- DragonFruit.Six.API/Properties/AssemblyInfo.cs
Add `UbisoftId` and `ProfileId` for apps wanting to save users. The ProfileId is the best thing to use to track a user when the change their username.
> AccountInfo params addition

- DragonFruit.Six.API.Demo/Program.cs
- DragonFruit.Six.API.Tests/AccountInfoTests.cs
- DragonFruit.Six.API.Tests/TestData.cs
- DragonFruit.Six.API.sln.DotSettings
- DragonFruit.Six.API/AccountInfo.cs
- DragonFruit.Six.API/Endpoints.cs
- DragonFruit.Six.API/Enums/LookupMethod.cs
- DragonFruit.Six.API/Enums/MatchResult.cs
- DragonFruit.Six.API/Enums/OperatorType.cs
- DragonFruit.Six.API/Enums/Platforms.cs
- DragonFruit.Six.API/Enums/Regions.cs
- DragonFruit.Six.API/Helpers/PlatformParser.cs
- DragonFruit.Six.API/Helpers/d6WebRequest.cs
- DragonFruit.Six.API/Processing/RawConvert.cs
- DragonFruit.Six.API/Processing/Strings.cs
- DragonFruit.Six.API/References.cs
- DragonFruit.Six.API/Stats/LoginInfo.cs
- DragonFruit.Six.API/Stats/OperatorStats.cs
- DragonFruit.Six.API/Stats/SeasonalStats.cs
Added ranked TimeUpdated, Kills, Deaths, NextRankMMR, PreviousRankMMR, SkillMean, SkillStdev, LastMatchResult, LastMatchMMRChange, LastMatchSkillChange, LastMatchSkillStdevChange.
SkillStdev and LastMatchSkillStdevChange possibly need renaming as I am not too sure on what "stdev" stands for.
Also, feel free to leave me with some 'todos' towards the repo.
> Add missing ranked stats

- DragonFruit.Six.API/Data/Deserializers/SeasonStatsDeserializer.cs
uses `Math.Clamp` to force a minimum of 1 for division purposes
> add abandons to seasonal wl

- DragonFruit.Six.API/Data/Extensions/UbisoftTokenExtensions.cs
didn't realise it was interfering with the method:
workaround: `UbisoftTokenExtensions.GetToken()` instead of `d6Client.GetToken()`
> rename GetToken method

- DragonFruit.Six.API.Demo/Program.cs
- DragonFruit.Six.API.Tests/Tests/UbisoftToolsTests.cs
- DragonFruit.Six.API/Data/Extensions/UserLocationInfoExtensions.cs
- DragonFruit.Six.API/Data/Requests/UserLocationInfoRequest.cs
- DragonFruit.Six.API/Data/UserLocationInfo.cs
Adds a new `UserLocationInfoRequest` that ubisoft exposes without needing a login. Extension `GetUserLocationInfo()` and tests included
> add ubisoft ip address tools

- DragonFruit.Six.API/Data/OperatorStats.cs
- DragonFruit.Six.API/Data/WeaponStats.cs
- DragonFruit.Six.API/Utils/OperatorData.cs
Now makes all the stats have their own proper naming structure, which now just needs to be checked over and made consistent.
Turns out while telerik is really annoying, it's possible to just type the model and the jsonproperty names out manually...
> Add jsonproperties to weapon and operator stats

- DragonFruit.Six.API/Data/Containers/ModeStatsContainer.cs
- DragonFruit.Six.API/Data/Containers/PlaylistStatsContainer.cs
- DragonFruit.Six.API/Data/Interfaces/IHasKd.cs
- DragonFruit.Six.API/Data/Interfaces/IHasWl.cs
- DragonFruit.Six.API/Data/OperatorStats.cs
- DragonFruit.Six.API/Data/SeasonStats.cs
- DragonFruit.Six.API/Data/StatsBase.cs
- DragonFruit.Six.API/Data/WeaponStats.cs
closes #166 
Adds 2 interfaces: `IHasKd` and `IHasWl` which are then consumed by `WeaponStats` and `StatsBase`, which then support jsonproperty inheritance.
Hopefully will stop codacy moaning about duplication -_-
Also fwiw the weapon stats were missing a Kd, so thats been added too :)
> add a set of interfaces for kd and wl based stats

- DragonFruit.Six.API/Data/Deserializers/OperatorStatsDeserializer.cs
- DragonFruit.Six.API/Data/OperatorStats.cs
This is to prepare for worst case scenario that the operator specific stats (like vigil's drones deceived) cannot be retrieved for newer characters (as there are no ubisoft operator datasheets with the keys used in)
other sites can't even find these, so they keep it simple and just go with kd/wl and other stats they don't need to do any extreme guesswork on.
Not a breaking change _per se_, just that extra null checks will need to be added
> allow operator actioncount to be nullable

- DragonFruit.Six.API/Dragon6Client.cs
Makes no changes to current usages, but with the mobile apps was causing the `UbiApiRequest`s to bypass the token injection
> add cancellationtoken overload to Dragon6Client

- DragonFruit.Six.API/Data/Deserializers/GeneralStatsDeserializer.cs
- DragonFruit.Six.API/Data/Deserializers/StatsDeserializer.cs
- DragonFruit.Six.API/Data/Extensions/StatsExtentions.cs
- DragonFruit.Six.API/Data/GeneralStats.cs
- DragonFruit.Six.API/Data/Requests/Base/BasicStatsRequest.cs
- DragonFruit.Six.API/Data/Requests/OperatorStatsRequest.cs
- DragonFruit.Six.API/Data/Requests/StatsRequest.cs
- DragonFruit.Six.API/Data/Requests/WeaponStatsRequest.cs
Fixes the `GeneralStats` showing up as not found
Related to #187
> refactor incorrect name

- DragonFruit.Six.Api/Dragon6Client.cs
I must have been lost when I wrote this...
This is the culprit behind http 500 errors the dragon6 servers have been facing. Current workaround was to purge the cache, and now i can see why that works
Note: if you only use the extensions this will make 0 impact, dragon6 uses its own custom requests that were being sent to the wrong overload
> Fix broken perform overload

- DragonFruit.Six.Api.Tests/Data/AccountLookupTests.cs
- DragonFruit.Six.Api/Dragon6Client.cs
- DragonFruit.Six.Api/Tokens/TokenBase.cs
Changes the `Expired` property of the token to return true when the token is within 5 mins of expiry. This will workaround any potential clock skews each side (client/ubisoft) could have.
> Add a clock skew safegard

- DragonFruit.Six.Api.Tests/Tokens/TokenExpiryTests.cs
- DragonFruit.Six.Api/Tokens/Dragon6Token.cs
- DragonFruit.Six.Api/Tokens/TokenBase.cs
this was the reason that the pc version was held back (microsoft rejected it because of this):
if we have a datetime of `01/01/0001 00:01:00 +00:00` and then try to use the old skewing system:
https://github.com/dragonfruitnetwork/dragon6-api/blob/d124aef321ef68c9adfa86a1b60e44af413032f1/DragonFruit.Six.Api/Tokens/TokenBase.cs#L21-L22
we would end up with... -5 minutes in a non-existent year. no surprise that causes an exception.
added a test to stop this kind of thing happening again
> prevent exceptions being thrown with new tokens

- DragonFruit.Six.Api.Tests/Utils/SeasonalRanksTests.cs
- DragonFruit.Six.Api/Containers/RankInfo.cs
- DragonFruit.Six.Api/Entities/SeasonStats.cs
- DragonFruit.Six.Api/Utils/SeasonalRanks.cs
Closes #247 by adding mmr boundaries. this does break current usages of the `SeasonalRanks` utility class.
> add mmr boundaries to RankInfo

- DragonFruit.Six.Api.Tests/Data/LegacyStatsTests.cs
- DragonFruit.Six.Api/Legacy/Entities/LegacyOperatorInfo.cs
- DragonFruit.Six.Api/Legacy/LegacyStatsExtensions.cs
- DragonFruit.Six.Api/Legacy/Requests/LegacyOperatorInfoRequest.cs
Metadata for all legacy operators can be fetched by calling `client.GetLegacyOperatorInfoAsync()`
> add operator metadata requests and extensions

- DragonFruit.Six.Api.Tests/Data/MultiPlatformTests.cs
- DragonFruit.Six.Api.Tests/DragonFruit.Six.Api.Tests.csproj
- DragonFruit.Six.Api/Seasonal/Entities/SeasonalStatsResponse.cs
- DragonFruit.Six.Api/Seasonal/SeasonStatsExtensions.cs
this error occurred because clients were able to load seasonal stats through the extension method which failed to split the query into platform-specific subrequests.
adds tests to ensure this doesn't fall through again
> fix seasonal stats extensions throwing due to platform mismatches

- DragonFruit.Six.Api.Tests/Data/SeasonalStatsTests.cs
- DragonFruit.Six.Api.Tests/DragonFruit.Six.Api.Tests.csproj
- DragonFruit.Six.Api/DragonFruit.Six.Api.csproj
- DragonFruit.Six.Api/Legacy/LegacyStatsExtensions.cs
- DragonFruit.Six.Api/Seasonal/Entities/SeasonalStats.cs
- DragonFruit.Six.Api/Seasonal/Enums/BoardType.cs
- DragonFruit.Six.Api/Seasonal/Enums/Region.cs
- DragonFruit.Six.Api/Seasonal/Requests/SeasonalStatsRecordRequest.cs
- DragonFruit.Six.Api/Seasonal/Requests/SeasonalStatsRequest.cs
- DragonFruit.Six.Api/Seasonal/SeasonStatsExtensions.cs
Closes #293
Adds support for batch lookups of users on a single platform over multiple seasons, boards and regions. Extensions support any account (regardless of platform) by partitioning into platforms and making a separate request for each.
Updates dependencies (closes #294) and adds some `EnumMemberAttribute`s to `BoardType`
> add skill records

- DragonFruit.Six.Api/Modern/Containers/RatioBackedStat.cs
- DragonFruit.Six.Api/Modern/Entities/ModernStatsBase.cs
Closes #304 
Converts all properties in the `Ratio` region to a backing field that uses the deserialized totals to calculate the totals. Because sometimes fractional values are returned, they are truncated for simplicity, but the original values are left in the event someone wants to do their own thing.
> create struct to handle modern stats ratio values

- DragonFruit.Six.Api/Dragon6Client.cs
A quick quality fix that will hopefully allow errors to not return aggregate exceptions with unparsable errors inside...
> wrap validate and process `throw` statements as tasks

- DragonFruit.Six.Api.Tests/Data/ModernStatsTests.cs
- DragonFruit.Six.Api/Modern/Containers/ModernModeStatsContainer.cs
- DragonFruit.Six.Api/Modern/Containers/ModernRoleStatsContainer.cs
- DragonFruit.Six.Api/Modern/Containers/WeaponSlot.cs
- DragonFruit.Six.Api/Modern/Entities/ModernStatsBase.cs
- DragonFruit.Six.Api/Modern/ModernStatsDeserializer.cs
- DragonFruit.Six.Api/Modern/Utils/JsonPathAttribute.cs
- DragonFruit.Six.Api/Modern/Utils/JsonPathConverter.cs
- DragonFruit.Six.Api/Modern/Utils/JsonPathSerializableAttribute.cs
custom converters are no longer decorated, and are setup at the extension method level. This will now allow consumers to re-serialize data to client without the containers **and** without dots in property names, which will break any typescript setup.
this also removes indexers for containers, as they are completely redundant and some enum values cannot be used. unlikely to affect anyone, but is _technically_ a breaking change.
Any class decorated with `JsonPathSerializableAttribute` will use the custom serializer, which will then look for a `JsonPathAttribute` before falling back to the default `JsonPropertyAttribute`. As previously, these are explicit opt-in converters, so will skip any property that it cannot get a property name for, or is unable to read/write to.
> change modern stats JPath handling

- DragonFruit.Six.Api/Accounts/Requests/UbisoftGeolocationRequest.cs
- DragonFruit.Six.Api/Dragon6Client.cs
- DragonFruit.Six.Api/DragonFruit.Six.Api.csproj
- DragonFruit.Six.Api/Services/Developer/Dragon6DeveloperApiRequest.cs
- DragonFruit.Six.Api/Services/Developer/Dragon6DeveloperClient.cs
- DragonFruit.Six.Api/UbiApiRequest.cs
This _finally_ makes the entire token fetching flow asynchronous, with almost no additional pressure when pulling it from the cache, thanks to `ValueTask`s and being able to hide the `OnExecutingAsync()` methods is also a bonus.
Only breaking change is the `RequestAccessToken` now returns a `ValueTask<IUbisoftToken>`, which means the method needs to be made async, which shouldn't be an issue.
> Update data library

- DragonFruit.Six.Api/Dragon6Client.cs
- DragonFruit.Six.Api/Services/Developer/Dragon6DeveloperClient.cs
Closes #320 and adds the `sessionId` to the GetToken parameters to make it easier to determine if a session needs to be updated from ubisoft
> change method signature to accept a sessionid and a task over valuetask

- DragonFruit.Six.Api.Tests/Utils/ServiceTests.cs
- DragonFruit.Six.Api/Accounts/UbisoftAccountExtensions.cs
- DragonFruit.Six.Api/Services/Geolocation/Geolocation.cs
- DragonFruit.Six.Api/Services/Geolocation/GeolocationExtensions.cs
- DragonFruit.Six.Api/Services/Geolocation/Requests/UbisoftGeolocationRequest.cs
- DragonFruit.Six.Api/Services/Geolocation/Requests/UbisoftSelfGeolocationRequest.cs
Closes #321
Adds the new geolocation api which can be accessed via extensions as seen in the tests (accepts either strings or `IPAddress`es):
https://github.com/dragonfruitnetwork/dragon6-api/blob/6473472754a060c028540d24351acba10941897e/DragonFruit.Six.Api.Tests/Utils/ServiceTests.cs#L22
Has also been tested and works with IPv6 addresses.
> Add geolocation api

- DragonFruit.Six.Api/Authentication/Entities/ClientTokenInjector.cs
- DragonFruit.Six.Api/Dragon6Client.cs
- DragonFruit.Six.Api/UbiApiRequest.cs
Renames `RequestAccessToken` to `RequestToken` and publicly exposes `Token` property of the token injector
> update client token injection to be accessible outside of the library

- DragonFruit.Six.Api/Modern/Containers/ModernStatsTrendPointCollection.cs
- DragonFruit.Six.Api/Modern/Entities/ModernStatsBase.cs
- DragonFruit.Six.Api/Modern/Entities/ModernStatsTrend.cs
- DragonFruit.Six.Api/Modern/Enums/TrendSpan.cs
- DragonFruit.Six.Api/Modern/Requests/ModernStatsRequest.cs
- DragonFruit.Six.Api/Modern/Requests/ModernStatsTrendRequest.cs
This fixes the errors that now occur due to ubisoft shutting down the current url that was being used by the api. It's been replaced with one that is basically the same with a couple extra query params that can be derived with information already known.
- Trends have been changed to a reduced set, and have min/max/mean values as well as the original data and a trendline set.
- Trends can also be selected daily or weekly, with weekly still being the default choice
This is an emergency fix, but adding summaries for specific seasons will now work and getting a list of all season summaries should be supported too.
> Fix ubi urls

- DragonFruit.Six.Api.Tests/Data/AccountLevelTests.cs
- DragonFruit.Six.Api/Accounts/Requests/AccountLevelRequest.cs
- DragonFruit.Six.Api/Authentication/Entities/ClientTokenAccessor.cs
- DragonFruit.Six.Api/Authentication/Entities/ClientTokenInjector.cs
- DragonFruit.Six.Api/Authentication/Entities/Dragon6Token.cs
- DragonFruit.Six.Api/Authentication/Entities/IUbisoftToken.cs
- DragonFruit.Six.Api/Authentication/Entities/UbisoftToken.cs
- DragonFruit.Six.Api/Authentication/Requests/UbisoftTokenRequest.cs
- DragonFruit.Six.Api/Authentication/UbisoftTokenExtensions.cs
- DragonFruit.Six.Api/Dragon6Client.cs
- DragonFruit.Six.Api/Exceptions/InvalidTokenException.cs
- DragonFruit.Six.Api/Seasonal/Requests/SeasonalStatsRecordRequest.cs
- DragonFruit.Six.Api/Seasonal/SeasonStatsExtensions.cs
- DragonFruit.Six.Api/Services/Developer/Dragon6DeveloperClient.cs
- DragonFruit.Six.Api/Services/Geolocation/Requests/UbisoftSelfGeolocationRequest.cs
- DragonFruit.Six.Api/UbiApiRequest.cs
Replaces the single token injector system with a set of multiple injectors that are stored in a `ConcurrentDictionary`.
This is to be used for ranked2 requests and level requests that cannot be performed with a token from a non-client app (i.e. needs to look like the actual game has made the request)
- Removed synchronous `GetUbiToken()` extensions 
- Added `UbisoftService` parameter to `GetUbiTokenAsync()` methods. It's optional but will fail if the user performs the request on a non `Dragon6Client` and doesn't provide one.
- Added `AppId` property to all tokens, which is autofilled on getting the token response.
- Hides the `Token` property from `ClientTokenInjector`. The `ClientTokenAccessor`'s `GetToken()` method should be used instead
- `Dragon6Client.GetToken()` has a different …
> Add service specific token injectors

- DragonFruit.Six.Api/Authentication/Entities/UbisoftToken.cs
You can now cast a `UbisoftToken` to a `UbisoftAccount`, as the token is an account with some login properties attached...
> Add more properties to ubisoft tokens

- DragonFruit.Six.Api/Modern/ModernStatsDeserializer.cs
- DragonFruit.Six.Api/Modern/ModernStatsExtensions.cs
- DragonFruit.Six.Api/Modern/Requests/ModernSeasonalStatsRequest.cs
- DragonFruit.Six.Api/Modern/Requests/ModernStatsRequest.cs
- DragonFruit.Six.Api/Modern/Utils/ModernPlatformUtils.cs
- DragonFruit.Six.Api/Modern/Utils/ModernSeason.cs
- Changes the season property in `ModernStatsRequest` to accept a struct that represents a season, `ModernSeason` (breaking)
- Adds additional checking when deciding what platform query to use
- Updates to container formats
- Removes the need to pass the initial request to the deserializer
> Further Modern stats updates
