README.md
I updated the example, just a bit more complete. Still not perfect, but they should be able to work it out from there and fix any issues
=> Updated the example

Dragon6-API/Processing/Alignments.cs, Dragon6-API/Processing/Consts.cs, Dragon6-API/Properties/AssemblyInfo.cs, Dragon6-API/Stats/PlayerStats.cs
New Stats:
- Penetration Kills
- Shots Fired
- Shots Connected
Maintenance:
- Updated Version Number
- Removed duplicated strings and moved it at the beginning of the alignment
=> add more stats and cleanup code

Dragon6-API/Dragon6-API.csproj, Dragon6-API/Helpers/PlatformParser.cs, Dragon6-API/Properties/AssemblyInfo.cs, Dragon6-API/References.cs, Dragon6-API/Verification/Server.cs
fix bugs with verification and rank names
=> verification update

.github/workflows/test.yml, Dragon6-API/Dragon6-API.csproj, Dragon6-API/References.cs
Update the references to work with `uint` instead of `int`
=> Consistency Updates

DragonFruit.Six.API.Demo/Program.cs, DragonFruit.Six.API.Tests/AccountInfoTests.cs, DragonFruit.Six.API.Tests/StatsTests.cs, DragonFruit.Six.API.sln.DotSettings, DragonFruit.Six.API/DragonFruit.Six.API.csproj, DragonFruit.Six.API/Endpoints.cs, DragonFruit.Six.API/Processing/RawConvert.cs, DragonFruit.Six.API/Processing/Strings.cs, DragonFruit.Six.API/Properties/AssemblyInfo.cs, DragonFruit.Six.API/References.cs, DragonFruit.Six.API/Stats/LoginInfo.cs, DragonFruit.Six.API/Stats/OperatorStats.cs, DragonFruit.Six.API/Stats/SeasonalStats.cs, DragonFruit.Six.API/Verification/Verification.cs
Added:
- 'Last Seen' time
- Session Count
- First time played
- Operator Gadget info and time played
Closes #38 and #39
(Already published to NuGet)
=> Add more stats

DragonFruit.Six.API/DragonFruit.Six.API.csproj, DragonFruit.Six.API/Processing/Strings.cs, README.md
Fixes the 4 stats strings that were incorrectly placed (closes #46).
Also updates the readme (closes #45) and the nuget icon (closes #42)
=> Fix Operator KD/WL

.travis.yml, Nuget.ps1
=> add auto deploy script

DragonFruit.Six.API/Data/Requests/TokenRequest.cs, DragonFruit.Six.API/DragonFruit.Six.API.csproj, DragonFruit.Six.API/Helpers/UbisoftAuthClientSerializer.cs
added a special ubisoft client serialiser that dumps a blank request with the right headers on
=> fix broken token client

DragonFruit.Six.API/Data/Deserializers/RankedSeasonStatsDeserializer.cs, DragonFruit.Six.API/Data/Extensions/SeasonStatsExtensions.cs, DragonFruit.Six.API/Data/OperatorStats.cs, DragonFruit.Six.API/Data/Requests/SeasonStatsRequest.cs, DragonFruit.Six.API/Data/SeasonStats.cs
add hoursplayed shortcut property to operatorstats
=> refactor rankedseasonstats to seasonstats

DragonFruit.Six.API.Demo/Program.cs, DragonFruit.Six.API.Tests/TestData.cs, DragonFruit.Six.API/Data/AccountInfo.cs, DragonFruit.Six.API/Data/Containers/UserIdentifierContainer.cs, DragonFruit.Six.API/Data/Deserializers/AccountInfoDeserializer.cs, DragonFruit.Six.API/Data/Deserializers/TokenDeserializer.cs, DragonFruit.Six.API/Data/Requests/AccountLoginInfoRequests.cs, DragonFruit.Six.API/Data/Requests/Base/PlatformSpecificRequest.cs, DragonFruit.Six.API/Data/Requests/PlayerLevelStatsRequest.cs, DragonFruit.Six.API/Data/Requests/SeasonStatsRequest.cs, DragonFruit.Six.API/DragonFruit.Six.API.csproj, DragonFruit.Six.API/Helpers/OperatorData.cs
closes #64 and bumps the dragonfruit common library
=> add identifiers container

DragonFruit.Six.API/Data/OperatorStats.cs, DragonFruit.Six.API/Helpers/OperatorData.cs
adds the property introduced by https://github.com/dragonfruitnetwork/Dragon6-Assets/pull/9
=> add operator order property

.github/workflows/codequality.yaml, .github/workflows/publish.yaml, .github/workflows/tests.yaml, README.md
Forgot to update the readme and for some reason rider loves to leave a space at the beginning of each actions file ¯\_(ツ)_/¯
=> Cleanup GitHub actions

DragonFruit.Six.API/Data/Extensions/UbisoftTokenExtensions.cs, DragonFruit.Six.API/Dragon6Client.cs
potential infinite loop could be caused by not filtering out token requests from stats requests
=> fix infinite loop

DragonFruit.Six.API/Data/Extensions/UbisoftTokenExtensions.cs, DragonFruit.Six.API/Data/Requests/Base/UbiApiRequest.cs, DragonFruit.Six.API/Dragon6Client.cs
closes #91 and fix header-related issues
=> Code Cleanup (2nd attempt)

DragonFruit.Six.API/Data/Requests/Base/PlatformSpecificRequest.cs, DragonFruit.Six.API/Data/Requests/PlayerLevelStatsRequest.cs, DragonFruit.Six.API/Data/Requests/TokenRequest.cs, DragonFruit.Six.API/Developer/Dragon6DeveloperClient.cs, DragonFruit.Six.API/Developer/Requests/DeveloperTokenRequest.cs, DragonFruit.Six.API/Dragon6Client.cs, DragonFruit.Six.API/DragonFruit.Six.API.csproj
Uses new features and removes potential issues with headers
=> API Framework Update

DragonFruit.Six.API/Data/AccountInfo.cs
Needs doing for the dragon6 site - anyone who wants to address an issue can do so even once merged
=> Add AccountInfo ToString override

README.md
=> Update Discord URL (for the badge)

CONTRIBUTING.md, README.md
=> add contribution guidelines

DragonFruit.Six.API/References.cs
=> Remove obsolete dictionaries

DragonFruit.Six.API/Data/Deserializers/GeneralStatsDeserializer.cs, DragonFruit.Six.API/Data/GeneralStats.cs, DragonFruit.Six.API/Data/Strings/General.cs
=> Remove unused key

DragonFruit.Six.API/Data/Deserializers/GeneralStatsDeserializer.cs, DragonFruit.Six.API/Data/GeneralStats.cs, DragonFruit.Six.API/Data/Requests/GeneralStatsRequest.cs, DragonFruit.Six.API/Data/Strings/General.cs
=> Add total blindkills

DragonFruit.Six.API/Data/Deserializers/GeneralStatsDeserializer.cs, DragonFruit.Six.API/Data/GeneralStats.cs, DragonFruit.Six.API/Data/Requests/GeneralStatsRequest.cs, DragonFruit.Six.API/Data/Strings/General.cs
=> add DBNO assists

DragonFruit.Six.API/Data/Deserializers/OperatorStatsDeserializer.cs, DragonFruit.Six.API/Data/OperatorStats.cs, DragonFruit.Six.API/Data/Requests/OperatorStatsRequest.cs, DragonFruit.Six.API/Data/Strings/Operator.cs
=> add operator experience gained

DragonFruit.Six.API/Data/Strings/Accounts.cs, DragonFruit.Six.API/Data/Strings/General.cs, DragonFruit.Six.API/Data/Strings/GeneralCasual.cs, DragonFruit.Six.API/Data/Strings/GeneralRanked.cs, DragonFruit.Six.API/Data/Strings/GeneralTraining.cs, DragonFruit.Six.API/Data/Strings/Login.cs, DragonFruit.Six.API/Data/Strings/Misc.cs, DragonFruit.Six.API/Data/Strings/Modes.cs, DragonFruit.Six.API/Data/Strings/Operator.cs, DragonFruit.Six.API/Data/Strings/Seasonal.cs, DragonFruit.Six.API/Data/Strings/Weapon.cs, DragonFruit.Six.API/Endpoints.cs
Completes the 3rd part and closes #138
(Was done with a regex search and replace so there should be no inconsistencies)
=> Convert properties of subclasses of "strings" to getters

DragonFruit.Six.API/Data/AccountActivity.cs, DragonFruit.Six.API/Data/Deserializers/AccountActivityDeserializer.cs, DragonFruit.Six.API/Data/Extensions/AccountActivityExtensions.cs, DragonFruit.Six.API/Data/Requests/AccountActivityRequest.cs, DragonFruit.Six.API/Data/Strings/Activity.cs
Supersedes #152 and closes #150
=> refactor accountlogininfo

DragonFruit.Six.API.sln.DotSettings, DragonFruit.Six.API/Data/Deserializers/WeaponStatsDeserializer.cs, DragonFruit.Six.API/Data/Requests/WeaponStatsRequest.cs, DragonFruit.Six.API/Data/Strings/Weapon.cs, DragonFruit.Six.API/Data/WeaponStats.cs, DragonFruit.Six.API/Enums/WeaponType.cs, DragonFruit.Six.API/References.cs
Closes #153 
Also removes the weaponclasses dictionary.
Note - these stats are really inaccurate so they shouldn't be used...
=> Add more weapon stats

DragonFruit.Six.API/Data/Containers/ModeStatsContainer.cs, DragonFruit.Six.API/Data/Deserializers/GeneralStatsDeserializer.cs, DragonFruit.Six.API/Data/GeneralStats.cs, DragonFruit.Six.API/Data/Requests/GeneralStatsRequest.cs, DragonFruit.Six.API/Data/Strings/Modes.cs
=> add mode specific stats

DragonFruit.Six.API.Demo/Program.cs, DragonFruit.Six.API.Tests.Common/TestData.cs, DragonFruit.Six.API.Tests/Tests/StatsTests.cs, DragonFruit.Six.API/Data/AccountActivity.cs, DragonFruit.Six.API/Data/AccountInfo.cs, DragonFruit.Six.API/Data/Containers/ModeStatsContainer.cs, DragonFruit.Six.API/Data/Containers/UserIdentifierContainer.cs, DragonFruit.Six.API/Data/Deserializers/GeneralStatsDeserializer.cs, DragonFruit.Six.API/Data/Extensions/AccountActivityExtensions.cs, DragonFruit.Six.API/Data/Extensions/GeneralStatsExtentions.cs, DragonFruit.Six.API/Data/Extensions/OperatorStatsExtensions.cs, DragonFruit.Six.API/Data/Extensions/PlayerLevelStatsExtensions.cs, DragonFruit.Six.API/Data/Extensions/SeasonStatsExtensions.cs, DragonFruit.Six.API/Data/Extensions/WeaponStatsExtensions.cs, DragonFruit.Six.API/Data/GeneralStats.cs, DragonFruit.Six.API/Data/OperatorStats.cs, DragonFruit.Six.API/Data/PlayerLevelStats.cs, DragonFruit.Six.API/Data/Requests/AccountActivityRequest.cs, DragonFruit.Six.API/Data/Requests/AccountInfoRequest.cs, DragonFruit.Six.API/Data/Requests/Base/BasicStatsRequest.cs, DragonFruit.Six.API/Data/Requests/Base/PlatformSpecificRequest.cs, DragonFruit.Six.API/Data/Requests/GeneralStatsRequest.cs, DragonFruit.Six.API/Data/Requests/PlayerLevelStatsRequest.cs, DragonFruit.Six.API/Data/Requests/SeasonStatsRequest.cs, DragonFruit.Six.API/Data/Strings/Modes.cs, DragonFruit.Six.API/Data/WeaponStats.cs, DragonFruit.Six.API/Exceptions/AccountPlatformException.cs
=> Add xmldocs

DragonFruit.Six.API.Tests/Tests/ServerStatusTests.cs, DragonFruit.Six.API/Data/Deserializers/AccountActivityDeserializer.cs, DragonFruit.Six.API/Data/Extensions/ServerStatusExtensions.cs, DragonFruit.Six.API/Data/Requests/AccountActivityRequest.cs, DragonFruit.Six.API/Data/Requests/ServerStatusRequest.cs, DragonFruit.Six.API/Data/ServerStatusReport.cs, DragonFruit.Six.API/Enums/ServerStatus.cs, DragonFruit.Six.API/Utils/PlatformParser.cs, DragonFruit.Six.API/Utils/UbisoftIdentifiers.cs
=> Re-add server status

DragonFruit.Six.API/Data/Deserializers/SeasonStatsDeserializer.cs, DragonFruit.Six.API/Data/SeasonStats.cs
just realised this was missing (¬_¬ )
=> add MaxRank info to seasonal stats

DragonFruit.Six.API/Data/Containers/ModeStatsContainer.cs, DragonFruit.Six.API/Data/Containers/PlaylistStatsContainer.cs, DragonFruit.Six.API/Data/OperatorStats.cs
should help automapped properties work propertly
=> make duration internal protected

Nuget.ps1
something that we do need (for sentry and other reflection-based systems)
=> add version to nuget build

DragonFruit.Six.API/Data/Extensions/AccountActivityExtensions.cs, DragonFruit.Six.API/Data/Extensions/AccountInfoExtensions.cs, DragonFruit.Six.API/Data/Extensions/GeneralStatsExtentions.cs, DragonFruit.Six.API/Data/Extensions/OperatorStatsExtensions.cs, DragonFruit.Six.API/Data/Extensions/PlayerLevelStatsExtensions.cs, DragonFruit.Six.API/Data/Extensions/SeasonStatsExtensions.cs, DragonFruit.Six.API/Data/Extensions/ServerStatusExtensions.cs, DragonFruit.Six.API/Data/Extensions/UbisoftTokenExtensions.cs, DragonFruit.Six.API/Data/Extensions/UserLocationInfoExtensions.cs, DragonFruit.Six.API/Data/Extensions/WeaponStatsExtensions.cs, DragonFruit.Six.API/Dragon6Client.cs
Resolves the review comment in #179
=> add cancellationtoken overloads to extension methods

DragonFruit.Six.API/Data/Requests/TokenRequest.cs, DragonFruit.Six.API/Dragon6Client.cs, DragonFruit.Six.API/DragonFruit.Six.API.csproj
Should resolve unit test sync errors
=> update data library

DragonFruit.Six.API/Utils/RatioUtils.cs
=> make ratioutils public

DragonFruit.Six.API/Enums/OperatorType.cs
Needed for modern stats library
=> mark operatortype as a flag enum

DragonFruit.Six.API/Data/Tokens/Dragon6Token.cs, DragonFruit.Six.API/Data/Tokens/TokenBase.cs, DragonFruit.Six.API/Data/Tokens/UbisoftToken.cs, DragonFruit.Six.API/Developer/Auth/DeveloperTokenResponse.cs
Again, this is for the modern stats api
=> add session id to tokens

DragonFruit.Six.Api/Entities/GeneralStats.cs, DragonFruit.Six.Api/Entities/OperatorStats.cs, DragonFruit.Six.Api/Entities/WeaponStats.cs
Closes #222
Added `DebuggerDisplay` for `GeneralStats`, `OperatorStats` and `WeaponStats`
=> DebuggerDisplay attribute for domain classes

DragonFruit.Six.Api.Tests/Data/AccountActivityTests.cs, DragonFruit.Six.Api.Tests/Utils/IpInfoTests.cs, DragonFruit.Six.Api/Extensions/AccountActivityExtensions.cs, DragonFruit.Six.Api/Extensions/UserLocationInfoExtensions.cs, DragonFruit.Six.Api/Requests/AccountActivityRequest.cs, DragonFruit.Six.Api/Requests/AccountInfoRequest.cs, DragonFruit.Six.Api/Requests/GeolocationRequest.cs
changes some of the names to improve consistency with their request counterparts
=> naming cleanups

DragonFruit.Six.Api/Services/Verification/AccountExtensions.cs
mainly done with the dragon6 site in mind...
=> expose more extensions

DragonFruit.Six.Api/Services/Verification/AccountExtensions.cs, DragonFruit.Six.Api/Services/Verification/Dragon6AccountInfo.cs
=> update api returned role response

DragonFruit.Six.Api/Entities/SeasonStats.cs
not sure how this was missed /shrug
=> use seasonid instead of rank for check

DragonFruit.Six.Api/Requests/OperatorStatsRequest.cs, DragonFruit.Six.Api/Requests/OperatorTrainingStatsRequest.cs, DragonFruit.Six.Api/Requests/WeaponTrainingStatsRequest.cs, DragonFruit.Six.Api/Strings/Stats/Modes.Hostage.cs, DragonFruit.Six.Api/Utils/StatsStringsUtils.cs
aims to improve readability and general codebase 'feel'
=> split training requests to own files

DragonFruit.Six.Api/Dragon6Client.cs, DragonFruit.Six.Api/Extensions/OperatorStatsExtensions.cs, DragonFruit.Six.Api/Extensions/WeaponStatsExtensions.cs, DragonFruit.Six.Api/Requests/AccountActivityRequest.cs, DragonFruit.Six.Api/Requests/AccountInfoRequest.cs, DragonFruit.Six.Api/Requests/BasicStatsRequest.cs, DragonFruit.Six.Api/Requests/OperatorStatsRequest.cs, DragonFruit.Six.Api/Requests/PlatformSpecificRequest.cs, DragonFruit.Six.Api/Requests/PlayerLevelStatsRequest.cs, DragonFruit.Six.Api/Requests/SeasonStatsRequest.cs, DragonFruit.Six.Api/Requests/StatsRequest.cs, DragonFruit.Six.Api/Requests/TokenRequest.cs, DragonFruit.Six.Api/Requests/UbiApiRequest.cs, DragonFruit.Six.Api/Requests/WeaponStatsRequest.cs, DragonFruit.Six.Api/Utils/StatsStringsUtils.cs
another PR to improve the style of the repo.
only breaking if people make custom requests (unlikely)
=> remove request base namespace (move up a directory)

DragonFruit.Six.Api/Extensions/AccountInfoExtensions.cs
Must have been missed when that extension was added 🤔
=> change new[] to yield

DragonFruit.Six.Api/Requests/WeaponTrainingStatsRequest.cs
Fixes the issues highlighted in https://github.com/dragonfruitnetwork/dragon6-api/runs/3038942745?check_suite_focus=true#step:6:871
=> Code Quality fixes

DragonFruit.Six.Api/Utils/SeasonalRanks.cs
=> change to use new ranked icons

DragonFruit.Six.Api/Dragon6Client.cs, DragonFruit.Six.Api/DragonFruit.Six.Api.csproj, DragonFruit.Six.Api/Utils/OperatorData.cs
This now forces the default serializer to `ApiJsonSerializer` and gives us better control over everything. Some protected ctors have been removed, and the User-Agent now uses a hyphen instead of a space
=> Update data api

DragonFruit.Six.Api/Dragon6Client.cs
makes some documentation more descriptive
=> update client xmldocs

.config/dotnet-tools.json, .github/workflows/codequality.yaml, codecutter.json
it's faster to use the linux version (now that's a thing)
=> move away from codecutter

DragonFruit.Six.Api/Utils/OperatorData.cs
=> add operatordata async method

DragonFruit.Six.Api/Dragon6Client.cs
don't know why i didn't read this properly :/
=> fix incorrect logic check

DragonFruit.Six.Api/Requests/TokenRequest.cs
(cherry picked from commit c82bf2c0cbb2947fc161de93b9491a42d8f3927e)
=> downgrade token request

DragonFruit.Six.Api/Tokens/TokenBase.cs
needed for some token sync stuff on the main server
=> publicly expose skewed expiry

DragonFruit.Six.Api.Tests/Data/SeasonalStatsTests.cs, DragonFruit.Six.Api/DragonFruit.Six.Api.csproj, DragonFruit.Six.Api/Endpoints.cs, DragonFruit.Six.Api/Seasonal/Entities/SeasonInfo.cs, DragonFruit.Six.Api/Seasonal/Requests/SeasonInfoRequest.cs, DragonFruit.Six.Api/Seasonal/SeasonStatsExtensions.cs
Adds models, requests and extensions for getting season names and colours used by the dragon6 programs
=> Add season info requests

DragonFruit.Six.Api.Tests/DragonFruit.Six.Api.Tests.csproj, DragonFruit.Six.Api/Authentication/Entities/ClientAccessToken.cs, DragonFruit.Six.Api/DragonFruit.Six.Api.csproj, DragonFruit.Six.Api/Modern/Containers/ModernModeStatsContainer.cs, DragonFruit.Six.Api/Modern/Containers/ModernRoleStatsContainer.cs, DragonFruit.Six.Api/Modern/Containers/ModernStatsTrendPeriod.cs, DragonFruit.Six.Api/Modern/Containers/WeaponGroup.cs, DragonFruit.Six.Api/Modern/Containers/WeaponSlot.cs, DragonFruit.Six.Api/Modern/Entities/ModernMapStats.cs, DragonFruit.Six.Api/Modern/Entities/ModernOperatorStats.cs, DragonFruit.Six.Api/Modern/Entities/ModernSeasonStats.cs, DragonFruit.Six.Api/Modern/Entities/ModernStatsBase.cs, DragonFruit.Six.Api/Modern/Entities/ModernStatsSummary.cs, DragonFruit.Six.Api/Modern/Entities/ModernStatsTrend.cs, DragonFruit.Six.Api/Modern/Entities/ModernWeaponStats.cs, DragonFruit.Six.Api/Modern/Enums/TrendSpan.cs, DragonFruit.Six.Api/Modern/Requests/ModernMapStatsRequest.cs, DragonFruit.Six.Api/Modern/Requests/ModernOperatorStatsRequest.cs, DragonFruit.Six.Api/Modern/Requests/ModernSeasonalStatsRequest.cs, DragonFruit.Six.Api/Modern/Requests/ModernStatsSummaryRequest.cs, DragonFruit.Six.Api/Modern/Requests/ModernStatsTrendRequest.cs, DragonFruit.Six.Api/Modern/Requests/ModernWeaponStatsRequest.cs, DragonFruit.Six.Api/Modern/Utils/JsonPathConverter.cs
Continues where #280 left off, cleaning up code headers by running a resharper cleanup
=> Cleanup code

DragonFruit.Six.Api.Tests/Data/ModernStatsTests.cs, DragonFruit.Six.Api/Dragon6Client.cs, DragonFruit.Six.Api/Enums/OperatorType.cs, DragonFruit.Six.Api/Modern/Containers/ModernModeStatsContainer.cs, DragonFruit.Six.Api/Modern/Enums/PlaylistType.cs, DragonFruit.Six.Api/Modern/ModernStatsExtensions.cs, DragonFruit.Six.Api/Modern/Requests/ModernStatsRequest.cs, DragonFruit.Six.Api/Modern/Utils/EnumUtils.cs
Closes #297 
Also fixes users with no recent activity causing a misplaced timeout error...
This creates a breaking change where playlist enum values have changed.
=> Add modern stats cancellation and (basic) unit tests

DragonFruit.Six.Api.Tests/Data/SeasonalStatsTests.cs, DragonFruit.Six.Api/Seasonal/Enums/BoardType.cs
Works towards #296 by adding support for deathmatch stats
=> Add deathmatch board id

DragonFruit.Six.Api/Modern/ModernStatsExtensions.cs, DragonFruit.Six.Api/Seasonal/SeasonStatsExtensions.cs
=> Add modern extensions xmldoc

DragonFruit.Six.Api/Modern/ModernStatsExtensions.cs, DragonFruit.Six.Api/Modern/Requests/ModernStatsRequest.cs
not actually needed, but ubi does have the offset on their site?
=> remove 1 day end offset

DragonFruit.Six.Api/Accounts/Entities/UbisoftAccountActivity.cs, DragonFruit.Six.Api/Legacy/Entities/LegacyModeStats.cs, DragonFruit.Six.Api/Legacy/Entities/LegacyOperatorStats.cs, DragonFruit.Six.Api/Legacy/Entities/LegacyPlaylistStats.cs, DragonFruit.Six.Api/Legacy/Entities/LegacyStats.cs, DragonFruit.Six.Api/Legacy/Entities/LegacyStatsBase.cs, DragonFruit.Six.Api/Legacy/Entities/LegacyWeaponStats.cs, DragonFruit.Six.Api/Legacy/LegacyStatsDeserializer.cs, DragonFruit.Six.Api/Modern/Entities/ModernStatsBase.cs, DragonFruit.Six.Api/Modern/Entities/ModernWeaponStats.cs
Closes #306 but goes in the opposite direction...
Allows aggregation to help with #296. Also improves consistency and makes it more CLS compliant
=> add apply method for adding seasonal stats to legacy playlist containers

DragonFruit.Six.Api/Legacy/Entities/LegacyPlaylistStats.cs
not essential for a release, but reads better so...
=> xmldoc fixes

DragonFruit.Six.Api/Modern/Entities/ModernOperatorInfo.cs
=> add [Column] annotations to operator info

DragonFruit.Six.Api/Modern/Entities/ModernOperatorInfo.cs
=> specify primary keys for modern operator info

DragonFruit.Six.Api/Dragon6Client.cs
adds logic to pass the newly expired session id to be passed back to the gettoken method, removing the need for any validation to be done by the producer of the token (apart from checking the session id)
=> add refetch logic to tokens

DragonFruit.Six.Api/DragonFruit.Six.Api.csproj
=> update data framework

.github/workflows/publish.yaml, DragonFruit.Six.Api/DragonFruit.Six.Api.csproj
=> Update publish workflow

DragonFruit.Six.Api/DragonFruit.Six.Api.csproj, DragonFruit.Six.Api/Modern/Enums/PlatformGroup.cs, DragonFruit.Six.Api/Modern/ModernStatsDeserializer.cs, DragonFruit.Six.Api/Modern/ModernStatsExtensions.cs, DragonFruit.Six.Api/Modern/Requests/ModernStatsRequest.cs
Addresses most of the entries in #338
=> Season updates

DragonFruit.Six.Api/Modern/Requests/ModernStatsRequest.cs
Aims to fix an error occurring in dragon6-android (the new one)
=> change modern stats endpoint url

DragonFruit.Six.Api/Legacy/Entities/LegacyPlaylistStats.cs
=> add matches played to include()

DragonFruit.Six.Api/Authentication/Entities/ClientTokenAccessor.cs, DragonFruit.Six.Api/Authentication/Entities/ClientTokenInjector.cs, DragonFruit.Six.Api/Dragon6Client.cs
Adds the ability to set a limit for how many times a token can be used before it's expired
=> add token usage limiter

DragonFruit.Six.Api.Tests/DragonFruit.Six.Api.Tests.csproj, DragonFruit.Six.Api/Authentication/Requests/UbisoftTokenRequest.cs, DragonFruit.Six.Api/DragonFruit.Six.Api.csproj
Adds a missing header to the authentication process and updates dependencies to use latest API library
=> Update account auth
